import { DashboardNavbar } from "@components/navbar/dashboard-navbar";
import { ViewAreas } from "@components/visx/view-areas";
import type { NextPage } from "next";
import Head from "next/head";
import { useMemo } from "react";
import { trpc } from "utils/trpc";

type GroupsMap = Map<
  string,
  {
    date: Date;
  }[]
>;

const Index: NextPage = () => {
  const { data: analytics } = trpc.useQuery(["analytics.get-analytics"]);

  const viewAreas = useMemo(() => {
    const map = analytics?.views.reduce((groups: GroupsMap, view) => {
      const date = view.created_at.toISOString().split("T")[0]!;
      if (!groups.has(date)) {
        groups.set(date, []);
      }
      groups.get(date)?.push({ date: view.created_at });
      return groups;
    }, new Map());
    if (!map) return [];
    const result: { close: number; date: string }[] = [];
    map.forEach((value, key) => {
      result.push({
        close: value.length,
        date: key,
      });
    });
    return result;
  }, [analytics]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col">
        <div className="flex flex-col space-y-4 px-24">
          <DashboardNavbar />
          <main>
            {analytics && (
              <div>
                <ViewAreas data={viewAreas} />
              </div>
            )}
          </main>
        </div>
      </div>
    </>
  );
};

export default Index;
