import { SocialMediaComponent } from "@components/social-medias-components";
import { NextPage } from "next";
import Head from "next/head";
import { useSyncExternalStore } from "react";
import { SocialMedia } from "utils/shared";

interface treeLocalStorage {
  slug?: string | null;
  bio?: string | null;
  theme?: string | null;
  image?: string | null;
  ads_enabled?: boolean;
  links?: {
    id: string;
    position: number;
    media: SocialMedia;
    url: string;
  }[];
}

function subscribe(callback: () => void) {
  window.addEventListener("storage", callback);
  return () => {
    window.removeEventListener("storage", callback);
  };
}

function useTreeLocalStorage() {
  return useSyncExternalStore(
    subscribe,
    () => window.localStorage.getItem("tree"),
    () => null
  );
}

const Index: NextPage = () => {
  const treeLocalStorage = useTreeLocalStorage();
  const tree: treeLocalStorage | null = treeLocalStorage
    ? JSON.parse(treeLocalStorage)
    : null;
  if (!tree) return <div>not tree dude</div>;
  return (
    <>
      <Head>
        <title>Preview </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col items-stretch space-y-4 p-6">
        <div className="flex flex-row items-center justify-center">
          <button className="btn">Switch View</button>
        </div>
        <div className="mockup-window flex grow flex-col border border-base-200 bg-base-300">
          <Preview tree={tree} />
        </div>
      </div>
    </>
  );
};

interface PreviewProps {
  tree: treeLocalStorage;
}
const Preview = ({ tree }: PreviewProps) => {
  return (
    <div data-theme={tree.theme} className="flex grow flex-col">
      <div className="flex min-h-full flex-col items-center bg-gradient-to-b from-base-100 to-base-300">
        <div className="flex w-full max-w-[760px] flex-col items-center space-y-4 p-10">
          {tree?.image ? (
            <div className="avatar w-24 drop-shadow-2xl">
              <img
                src={`${tree.image}?${performance.now()}`}
                className="h-auto w-auto rounded-full"
              />
            </div>
          ) : (
            <div className="avatar placeholder drop-shadow-2xl">
              <div className="w-24 rounded-full bg-base-100"></div>
            </div>
          )}
          <h1 className="text-lg font-bold">{tree.slug}</h1>
          {tree.bio && <h2 className="text-md text-justify">{tree.bio}</h2>}
          <div className="flex w-full flex-col items-center space-y-2 py-4 ">
            {tree?.links?.map((link) => (
              <a
                className="btn btn-lg flex w-full normal-case"
                key={link.id}
                href={link.url}
                target="_blank"
                rel="noreferrer"
              >
                <SocialMediaComponent
                  media={link.media}
                  className="flew-row relative flex w-full items-center justify-center font-light"
                  iconClassName="absolute left-0 text-2xl"
                />
              </a>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Index;
