import type { NextPage } from "next";
import Head from "next/head";
import { useSession, signOut } from "next-auth/react";
import Link from "next/link";
import Image from "next/future/image";

const Index: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen">
        <div className="flex flex-col px-24">
          <div className="flex flex-row p-6 items-center">
            <div className="flex flew-row flex-1 items-center justify-start space-x-10">
              <div className="text-4xl font-bold">Folllow</div>
              <a className="font-bold hover:opacity-75 hover:cursor-pointer">
                Features
              </a>
            </div>

            <div className="flex flew-row items-center justify-start space-x-10">
              {!session ? (
                <Link href="/sign-in" passHref>
                  <a className="btn btn-primary normal-case">Sign In</a>
                </Link>
              ) : (
                <div className="flex flex-row space-x-8 items-center">
                  <Link href="/dashboard" passHref>
                    <a className="font-bold hover:opacity-75">Dashboard</a>
                  </Link>
                  <div className="dropdown dropdown-end">
                    {session.user?.image ? (
                      <label
                        tabIndex={0}
                        className="avatar w-12 hover:cursor-pointer"
                      >
                        <Image
                          src={session.user.image}
                          className="w-auto h-auto mask mask-hexagon"
                        />
                      </label>
                    ) : (
                      <label
                        tabIndex={0}
                        className="avatar placeholder w-12 hover:cursor-pointer"
                      >
                        <div className="bg-base-200 rounded-full w-24 mask mask-hexagon"></div>
                      </label>
                    )}
                    <ul
                      tabIndex={0}
                      className="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52"
                    >
                      <li>
                        <a>Settings</a>
                      </li>
                      <li onClick={() => signOut()}>
                        <a>Log out</a>
                      </li>
                    </ul>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Index;
