import type { NextPage } from "next";
import Head from "next/head";
import { useSession, signOut } from "next-auth/react";
import Link from "next/link";

const Index: NextPage = () => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col">
        <div className="flex flex-col px-24">
          <div className="flex flex-row items-center p-6">
            <div className="flew-row flex flex-1 items-center justify-start space-x-10">
              <div className="text-4xl font-bold">Folllow</div>
              <a className="font-bold hover:cursor-pointer hover:opacity-75">
                Features
              </a>
            </div>

            <div className="flew-row flex items-center justify-start space-x-10">
              {!session ? (
                <Link href="/sign-in" passHref>
                  <a role="button" className="btn btn-primary normal-case">
                    Sign In
                  </a>
                </Link>
              ) : (
                <div className="flex flex-row items-center space-x-8">
                  <Link href="/dashboard" passHref>
                    <a className="font-bold hover:opacity-75">Dashboard</a>
                  </Link>
                  <div className="dropdown dropdown-end">
                    {session.user?.image ? (
                      <label
                        tabIndex={0}
                        className="avatar w-12 hover:cursor-pointer"
                      >
                        <img
                          src={session.user.image}
                          className="mask mask-hexagon h-auto w-auto"
                        />
                      </label>
                    ) : (
                      <label
                        tabIndex={0}
                        className="avatar placeholder w-12 hover:cursor-pointer"
                      >
                        <div className="mask mask-hexagon w-24 rounded-full bg-base-200"></div>
                      </label>
                    )}
                    <ul
                      tabIndex={0}
                      className="dropdown-content menu rounded-box w-52 bg-base-100 p-2 shadow"
                    >
                      <li role="button">
                        <a>Settings</a>
                      </li>
                      <li role="button" onClick={() => signOut()}>
                        <a>Log out</a>
                      </li>
                    </ul>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Index;
