import type {
  GetServerSidePropsContext,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import Head from "next/head";
import { useSession, signOut, getProviders, signIn } from "next-auth/react";
import Link from "next/link";
import Image from "next/future/image";

const Index: NextPage<ServerSideProps> = ({ providers }) => {
  if (!providers) return <div>No provider found!</div>;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen">
        {Object.values(providers).map((provider) => (
          <div key={provider.name}>
            <button onClick={() => signIn(provider.id)}>
              Sign in with {provider.name}
            </button>
          </div>
        ))}
      </div>
    </>
  );
};

type ServerSideProps = InferGetServerSidePropsType<typeof getServerSideProps>;
export async function getServerSideProps(context: GetServerSidePropsContext) {
  const providers = await getProviders();
  return {
    props: { providers },
  };
}

export default Index;
